import type { ThemeConfig } from 'antd';

export const themeConfig: ThemeConfig = {
  token: {
    colorPrimary: '#6366f1',
    colorPrimaryHover: '#4f46e5',
    colorPrimaryActive: '#4338ca',
    colorBgContainer: '#ffffff',
    colorBgLayout: '#f1f5f9',
    colorBgElevated: '#ffffff',
    colorBorder: '#e2e8f0',
    colorBorderSecondary: '#f1f5f9',
    colorText: '#0f172a',
    colorTextSecondary: '#475569',
    colorTextTertiary: '#94a3b8',
    colorSuccess: '#10b981',
    colorWarning: '#f59e0b',
    colorError: '#ef4444',
    colorInfo: '#3b82f6',
    borderRadius: 8,
    borderRadiusSM: 6,
    borderRadiusLG: 12,
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans SC', sans-serif",
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 30,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    fontSizeHeading5: 14,
    lineHeight: 1.6,
    lineHeightSM: 1.5,
    lineHeightLG: 1.5,
    lineHeightHeading1: 1.3,
    lineHeightHeading2: 1.35,
    lineHeightHeading3: 1.4,
    lineHeightHeading4: 1.5,
    lineHeightHeading5: 1.5,
    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 44,
    paddingContentVertical: 24,
    paddingContentHorizontal: 24,
    paddingSM: 12,
    paddingMD: 16,
    paddingLG: 24,
    marginSM: 12,
    marginMD: 16,
    marginLG: 24,
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    boxShadowSecondary: '0 4px 12px rgba(0,0,0,0.08)',
  },
  components: {
    Layout: {
      headerBg: '#ffffff',
      headerHeight: 56,
      headerPadding: '0 24px',
      siderBg: '#0f172a',
      triggerBg: '#0f172a',
      triggerHeight: 48,
      bodyBg: '#f1f5f9',
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: '#cbd5e1',
      itemHoverBg: '#1e293b',
      itemHoverColor: '#ffffff',
      itemSelectedBg: '#1e293b',
      itemSelectedColor: '#ffffff',
      itemActiveBg: '#1e293b',
      subMenuItemBg: 'transparent',
      popupBg: '#0f172a',
      itemHeight: 44,
      itemBorderRadius: 8,
      iconSize: 18,
      iconMarginInlineEnd: 10,
      horizontalItemSelectedColor: '#6366f1',
    },
    Card: {
      headerBg: '#ffffff',
      headerHeight: 56,
      paddingLG: 24,
      actionsBg: '#ffffff',
      borderRadiusLG: 8,
    },
    Table: {
      headerBg: '#f8fafc',
      headerColor: '#0f172a',
      headerSortActiveBg: '#f1f5f9',
      headerSortHoverBg: '#f1f5f9',
      rowHoverBg: '#f8fafc',
      borderColor: '#f1f5f9',
      cellFontSize: 13,
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      footerBg: '#ffffff',
    },
    Button: {
      borderRadius: 6,
      borderRadiusLG: 8,
      borderRadiusSM: 4,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
      paddingContentHorizontal: 16,
      paddingContentHorizontalLG: 24,
      paddingContentHorizontalSM: 12,
      fontSize: 14,
      fontSizeLG: 16,
      fontSizeSM: 13,
    },
    Form: {
      labelColor: '#475569',
      labelFontSize: 14,
      itemMarginBottom: 20,
    },
    Input: {
      borderRadius: 6,
      paddingBlock: 6,
      paddingInline: 12,
      colorBgContainer: '#ffffff',
    },
    Select: {
      borderRadius: 6,
      controlHeight: 36,
      optionSelectedBg: '#eef2ff',
    },
    Tag: {
      borderRadius: 4,
      fontSizeSM: 12,
      lineHeightSM: 1.5,
    },
    Tabs: {
      cardBg: '#ffffff',
      itemColor: '#475569',
      itemSelectedColor: '#6366f1',
    },
    Modal: {
      headerBg: '#ffffff',
      contentBg: '#ffffff',
      footerBg: '#ffffff',
    },
    Notification: {
      width: 400,
    },
    Switch: {
      trackHeight: 22,
    },
    Pagination: {
      itemSize: 32,
    },
  },
};
